name: Reusable workflow example

on:
  workflow_call:
    inputs:
      project_type:
        required: true
        type: string
    secrets:
      account:
        required: true

jobs:
  job_test_tag_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '11'

      - name: Get develop account
        if: ${{inputs.project_type == 'DEVELOP'}}
        run: echo ${{ secrets.TEST_ACCOUNT }}

      - name: Get production account
        if: ${{inputs.project_type == 'PRODUCTION'}}
        run: echo ${{ secrets.TEST_ACCOUNT_PROD }}

      - uses: actions/download-artifact@v3
        with:
          name: code-coverage-report-artifact
          path: target/site/jacoco

      - run: cat target/site/jacoco/jacoco.csv
      - name: Get total coverage percent
        run: |
          echo "total_coverage=$(python scripts/GetTotalPercentage.py 'target/site/jacoco/jacoco.csv')" >> "$GITHUB_ENV"

      - name: Comment
        run: echo "## Total code coverage report is ${{env.total_coverage}}"

      - run: echo "ğŸ current project type is ${{inputs.project_type}}."

      - run: echo "ğŸ secret_account is ${{secrets.account}}."

      - name: Run Junit Test-Job2-a
        run: |
          mvn clean
          mvn --batch-mode test

      - run: echo "ğŸ called job's status is ${{ job.status }}."

